// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txzafiuajwjsjqbpplqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4emFmaXVhandqc2pxYnBwbHFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0MTI0OTQsImV4cCI6MjA1NTk4ODQ5NH0.G22NRiTLQrL8zzBNwhLQwSWM9vwasF1-QFyLPAQ7Epk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);